[package]
name = "sonic-platformer"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.1"
glam = {version = "0.19.0", features = ["mint"]}
mint = "0.5"
legion = "0.4.0"