[package]
name = "sonic-platformer"
version = "0.0.4"
edition = "2018"

[dependencies]
ggez = "0.6.1"
glam = {version = "0.19.0", features = ["mint"]}
mint = "0.5"
legion = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
