[0]
tiles = [0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]

[1]
tiles = [1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]

[2]
tiles = [2, 3, 0, 0, 0, 0, 0, 0,
         2, 2, 2, 3, 0, 0, 0, 0,
         2, 2, 2, 2, 2, 3, 0, 0,
         2, 2, 2, 2, 2, 2, 2, 3]

