[0]
tiles = [0, 0, 0, 0]
height_map = 0
angle = 0.0

[1]
tiles = [1, 1, 4, 4]
height_map = 0
angle = 0.0

[2]
tiles = [4, 4, 4, 4]
height_map = 0
angle = 0.0

[3]
tiles = [5, 2, 4, 4]
height_map = 0
angle = 0.0

[4]
tiles = [3, 6, 4, 4]
height_map = 0
angle = 0.0
