[package]
name = "mapgen"
authors = ["Lucas Vieira <lucasvieira@protonmail.com>"]
version = "0.0.1"
edition = "2018"
default-run = "mapgen"
autobins = false

[[bin]]
name = "mapgen"
path = "src/main.rs"

[dependencies]
image = "0.23"
anyhow = "1.0"
